### ISSUE TITLE
Getting an error when running script

### ISSUE THREAD

**Issue by X1pheR** [Wintermute0110/NARS#1]
Hi, I think this script is exactly what I'm looking for. I downloaded and installed latest version of Python x64 for Windows. I'm running Windows 8.1 x64. I was trying it out but I get an error message. Can you please help? The error I'm getting is:

C:\Software\Portables\XBMC-rom-utils-master>xru-console.py list-tags snes
File "C:\Software\Portables\XBMC-rom-utils-master\xru-console.py", line 55
print k
^
SyntaxError: Missing parentheses in call to 'print'

C:\Software\Portables\XBMC-rom-utils-master>

I've configured the xml file as below. Only the snes part with rom and dat path. I've also tried without surrounding " in the paths but same error.

<ROMcollections>

<collection name="SNES NoIntro" shortname="snes">
<NoIntroDat>"C:\Emulation\Dats\Nintendo - Super Nintendo Entertainment System (20150215-231121_CM).dat"</NoIntroDat>
<ROMsSource>"C:\Emulation\Roms\Nintendo - Super Nintendo Entertainment System"</ROMsSource>
<ROMsDest>"C:\Emulation\Roms\Nintendo - Super Nintendo Entertainment System (Sorted)"</ROMsDest>
<ThumbsSource>/home/xbmc/roms/ArtWork/nintendo-snes-boxes/</ThumbsSource>
<FanartSource>/home/xbmc/roms/ArtWork/nintendo-snes-snaps/</FanartSource>
<ThumbsDest>/home/xbmc/NUC-remote/ROMs/ArtWork/nintendo-snes-thumbs/</ThumbsDest>
<FanartDest>/home/xbmc/NUC-remote/ROMs/ArtWork/nintendo-snes-fanart/</FanartDest>
<filterUpTags>Europe, World, Rev 1</filterUpTags>
<filterDownTags>Japan, Beta, Proto, France</filterDownTags>
<includeTags>Europe, USA</includeTags>
<excludeTags>Japan</excludeTags>
</collection>

<collection name="Sega Mega Drive NoIntro" shortname="genesis">
<ROMsSource>/home/xbmc/roms/roms-sega-genesis/</ROMsSource>
<ROMsDest>/home/xbmc/NUC-remote/ROMs/roms-sega-genesis/</ROMsDest>
<filterUpTags>Europe, World, Rev 1</filterUpTags>
<filterDownTags>Japan, Beta, Proto</filterDownTags>
<includeTags>Europe, USA</includeTags>
<excludeTags>Japan</excludeTags>
</collection>
</ROMcollections>

I've only configured the rom and dat path just to test it. But eventually I would like to add all artwork sets I have. I don't know what the Thumbs and Fanart is supposed to be but below are the folders I have populated with artwork/media. Can I configure these? And how?

Advert
Background
Banner
Boxes
Boxes_3D
Cartridges
Manuals
Snaps
Titles
Videos

Also posted at:
http://forum.kodi.tv/showthread.php?tid=200892

**Comment by Wintermute0110** [comment]
Hi,

One user at last!!! Thanks for using XRU.

Problem is that XRU was developed and meant to be run under Python2. You are using Python3 and one of the changes in Python3 is that print() requires parentheses. Just to confirm, can you please run python --version and post results.

In these months my Python knowledge has increased quite some. Software needs some refactoring and an upgrade to Python3. 

Also, from MAME 0.162 MESS and MAME are now part of the same executable and the XML han undergone some changes. XRU-console should work as usual but XRU-mame will need some work to work in MAME 0.162 and up. Be warned of this.

ASAP I will start the refactoring and code upgrade to Python3. It would be nice if you can do some testing and give your opinion about strong and weak aspects of the software and new features you may consider useful. Please open as many issues in Github as necessary.

I will do a quick reply in the forum as well to notify people in the Kodi forum.

**Comment by Wintermute0110** [comment]
Forgot to say: I check Github more frequently than Kodi forum. Please post stuff about software problems here. If you have feature requests or general discussion please post both sites. Thanks.
